class ErrorCode:
    """에러 코드 정의

    시스템 전체에서 사용하는 표준 에러 코드를 정의합니다.
    형식: {카테고리}_{순번}
    """

    # 사용자 관련 (USER_xxx)
    USER_NOT_FOUND = "USER_001"
    USER_ALREADY_EXISTS = "USER_002"
    INVALID_CREDENTIALS = "USER_003"
    USER_PERMISSION_DENIED = "USER_004"

    # 게시글 관련 (POST_xxx)
    POST_NOT_FOUND = "POST_001"
    POST_PERMISSION_DENIED = "POST_002"
    POST_AUTHOR_NOT_FOUND = "POST_003"

    # 댓글 관련 (COMMENT_xxx)
    COMMENT_NOT_FOUND = "COMMENT_001"
    COMMENT_PERMISSION_DENIED = "COMMENT_002"
    COMMENT_POST_MISMATCH = "COMMENT_003"
    COMMENT_AUTHOR_NOT_FOUND = "COMMENT_004"

    # 인증 관련 (AUTH_xxx)
    UNAUTHORIZED = "AUTH_001"
    TOKEN_EXPIRED = "AUTH_002"
    TOKEN_INVALID = "AUTH_003"
    INVALID_AUTH_HEADER = "AUTH_004"
    TOKEN_USER_NOT_FOUND = "AUTH_005"

    # 권한 관련 (PERMISSION_xxx)
    FORBIDDEN = "PERMISSION_001"
    ACCESS_DENIED = "PERMISSION_002"

    # 요청 관련 (REQUEST_xxx)
    BAD_REQUEST = "REQUEST_001"
    VALIDATION_ERROR = "REQUEST_002"
    INVALID_INPUT = "REQUEST_003"

    # 서버 관련 (SERVER_xxx)
    INTERNAL_SERVER_ERROR = "SERVER_001"
    UNEXPECTED_ERROR = "SERVER_002"
